# Generated by Django 5.2.4 on 2025-08-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=223, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=223, verbose_name='Название')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=223, verbose_name='Название')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=223, verbose_name='Название')),
                ('cover', models.ImageField(upload_to='media/products_image', verbose_name='Обложка')),
                ('area', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Кол/во м²')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('promo_video', models.FileField(upload_to='media/product_promo_video', verbose_name='Промо-ролик')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.city', verbose_name='Город')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимости',
            },
        ),
    ]
