# Generated by Django 5.2.4 on 2025-08-02 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='estate',
            name='geo',
            field=models.TextField(blank=True, null=True, verbose_name='Гео'),
        ),
        migrations.AddField(
            model_name='estate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/additional_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.estate')),
            ],
        ),
    ]
